"""Write a hashed lock from exact pins: every published file's sha256 for each pinned version.

    python interop/py/lock.py                       # interop/py/requirements.in -> requirements.lock
    python interop/py/lock.py IN OUT                # any other pin file

The oracles install with `pip install --require-hashes --no-deps --only-binary :all:`, so a lock
must list every package (dependencies included) with the hashes of every file pip may pick on
any platform. Hashes come from PyPI's JSON API for the pinned version; run this only when a pin
changes, and review the diff.
"""

import json
import pathlib
import sys
import urllib.request

HERE = pathlib.Path(__file__).parent


def lock(src: pathlib.Path, dst: pathlib.Path):
    lines = [
        f"# Generated by interop/py/lock.py from {src.name}. Do not edit by hand.",
        "# Every published file of each pinned version is listed, so one lock serves Linux, macOS and Windows.",
    ]
    for raw in src.read_text().splitlines():
        spec = raw.split("#", 1)[0].strip()
        if not spec:
            continue
        name, version = spec.split("==")
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json") as r:
            doc = json.load(r)
        hashes = sorted({f["digests"]["sha256"] for f in doc["urls"]})
        lines.append(f"{name}=={version} \\")
        cont = " \\"
        lines.extend(f"    --hash=sha256:{h}" + (cont if i < len(hashes) - 1 else "") for i, h in enumerate(hashes))
    dst.write_text("\n".join(lines) + "\n", newline="\n")


if __name__ == "__main__":
    args = sys.argv[1:]
    if args:
        lock(pathlib.Path(args[0]), pathlib.Path(args[1]))
    else:
        lock(HERE / "requirements.in", HERE / "requirements.lock")
